import type { DocumentLanguage } from "./document-language";

type InterfaceCopy = {
  subtitle: string;
  document: string;
  template: string;
  palette: string;
  originalColor: string;
  customColor: string;
  language: string;
  importJson: string;
  example: string;
  reset: string;
  preparingPdf: string;
  downloadPdf: string;
  downloadCurrent: string;
  downloadCurrentHint: string;
  downloadPack: string;
  downloadPackHint: string;
  preparingPack: string;
  packReady: string;
  currentPackReady: string;
  packError: string;
  resetConfirm: string;
  previewError: string;
  jsonImported: string;
  importError: string;
  personal: string;
  letterTitle: string;
  letterActive: string;
  letterAnnex: string;
  date: string;
  subject: string;
  recipient: string;
  greeting: string;
  paragraphs: string;
  closing: string;
  planTitle: string;
  planActive: string;
  planAnnex: string;
  previewPreparing: string;
  previewUpdating: string;
  exactPreview: string;
};

export type FormCopy = {
  fullName: string;
  jobTitle: string;
  phone: string;
  address: string;
  relocation: string;
  birthDate: string;
  maritalStatus: string;
  drivingLicence: string;
  nationalService: string;
  region: string;
  country: string;
  applicationInfo: string;
  objective: string;
  skills: string;
  skill: string;
  add: string;
  remove: string;
  languages: string;
  french: string;
  english: string;
  arabic: string;
  german: string;
  spanish: string;
  fluentExample: string;
  experience: string;
  training: string;
  education: string;
  volunteering: string;
  certifications: string;
  interests: string;
  references: string;
  dates: string;
  place: string;
  title: string;
  employer: string;
  achievements: string;
  addLine: string;
  delete: string;
  institution: string;
  acquiredSkills: string;
  option: string;
  equivalence: string;
  noItems: string;
  recipientPlaceholder: string;
  greetingPlaceholder: string;
};

const commonDownloadHint = "FR · EN · ES · DE · IT · 中文 · AR";

export const INTERFACE_COPY: Record<DocumentLanguage, InterfaceCopy> = {
  fr: {
    subtitle: "CV · Lettres de motivation · Plan professionnel · PDF multilingue sélectionnable",
    document: "Document",
    template: "Modèle",
    palette: "Couleur du modèle",
    originalColor: "Couleur originale",
    customColor: "Couleur personnalisée",
    language: "Langue du document",
    importJson: "Importer JSON",
    example: "Exemple",
    reset: "Réinitialiser",
    preparingPdf: "Préparation PDF",
    downloadPdf: "Télécharger PDF",
    downloadCurrent: "Modèle actuel · 7 langues (.zip)",
    downloadCurrentHint: commonDownloadHint,
    downloadPack: "Télécharger le pack complet (.zip)",
    downloadPackHint: "81 PDF · modèles arabes réservés à l’arabe",
    preparingPack: "Création du pack",
    packReady: "Pack téléchargé : 81 PDF, dont 4 modèles arabes dédiés.",
    currentPackReady: "Modèle actuel téléchargé dans les 7 langues.",
    packError: "Impossible de créer le pack complet.",
    resetConfirm: "Réinitialiser les données françaises ?",
    previewError: "Impossible de générer l’aperçu PDF.",
    jsonImported: "JSON importé :",
    importError: "Erreur inconnue pendant l’import.",
    personal: "Informations personnelles",
    letterTitle: "Lettre de motivation",
    letterActive: "Ces champs alimentent directement la lettre de motivation sélectionnée.",
    letterAnnex: "Conservée comme annexe lorsque le document actif est un CV.",
    date: "Date",
    subject: "Objet",
    recipient: "Destinataire",
    greeting: "Salutation",
    paragraphs: "Paragraphes",
    closing: "Formule de politesse",
    planTitle: "Plan de développement professionnel",
    planActive: "Ces actions alimentent directement le modèle Advises.",
    planAnnex: "Conservé comme annexe modifiable lorsque le document actif est un CV.",
    previewPreparing: "Préparation de l’aperçu PDF…",
    previewUpdating: "Mise à jour du PDF…",
    exactPreview: "Aperçu du PDF réel — le téléchargement utilise exactement ce même document.",
  },
  en: {
    subtitle: "Résumé · Cover letters · Professional plan · Selectable multilingual PDF",
    document: "Document",
    template: "Template",
    palette: "Template color",
    originalColor: "Original color",
    customColor: "Custom color",
    language: "Document language",
    importJson: "Import JSON",
    example: "Example",
    reset: "Reset",
    preparingPdf: "Preparing PDF",
    downloadPdf: "Download PDF",
    downloadCurrent: "Current template · 7 languages (.zip)",
    downloadCurrentHint: commonDownloadHint,
    downloadPack: "Download complete pack (.zip)",
    downloadPackHint: "81 PDFs · Arabic templates are Arabic-only",
    preparingPack: "Building pack",
    packReady: "Pack downloaded: 81 PDFs, including 4 dedicated Arabic templates.",
    currentPackReady: "Current template downloaded in all 7 languages.",
    packError: "Unable to create the complete pack.",
    resetConfirm: "Reset the English data?",
    previewError: "Unable to generate the PDF preview.",
    jsonImported: "JSON imported:",
    importError: "Unknown import error.",
    personal: "Personal information",
    letterTitle: "Cover letter",
    letterActive: "These fields directly populate the selected cover letter.",
    letterAnnex: "Kept as an editable annex while a résumé template is active.",
    date: "Date",
    subject: "Subject",
    recipient: "Recipient",
    greeting: "Greeting",
    paragraphs: "Paragraphs",
    closing: "Closing",
    planTitle: "Professional development plan",
    planActive: "These actions directly populate the Advises template.",
    planAnnex: "Kept as an editable annex while a résumé template is active.",
    previewPreparing: "Preparing the PDF preview…",
    previewUpdating: "Updating PDF…",
    exactPreview: "Real PDF preview — the download uses this exact same document.",
  },
  es: {
    subtitle:
      "Currículum · Cartas de presentación · Plan profesional · PDF multilingüe seleccionable",
    document: "Documento",
    template: "Plantilla",
    palette: "Color de la plantilla",
    originalColor: "Color original",
    customColor: "Color personalizado",
    language: "Idioma del documento",
    importJson: "Importar JSON",
    example: "Ejemplo",
    reset: "Restablecer",
    preparingPdf: "Preparando PDF",
    downloadPdf: "Descargar PDF",
    downloadCurrent: "Plantilla actual · 7 idiomas (.zip)",
    downloadCurrentHint: commonDownloadHint,
    downloadPack: "Descargar paquete completo (.zip)",
    downloadPackHint: "81 PDF · plantillas árabes solo en árabe",
    preparingPack: "Creando paquete",
    packReady: "Paquete descargado: 81 PDF, con 4 plantillas árabes dedicadas.",
    currentPackReady: "Plantilla actual descargada en los 7 idiomas.",
    packError: "No se pudo crear el paquete completo.",
    resetConfirm: "¿Restablecer los datos en español?",
    previewError: "No se pudo generar la vista previa del PDF.",
    jsonImported: "JSON importado:",
    importError: "Error desconocido durante la importación.",
    personal: "Información personal",
    letterTitle: "Carta de presentación",
    letterActive: "Estos campos completan directamente la carta seleccionada.",
    letterAnnex: "Se conserva como anexo editable cuando el documento activo es un currículum.",
    date: "Fecha",
    subject: "Asunto",
    recipient: "Destinatario",
    greeting: "Saludo",
    paragraphs: "Párrafos",
    closing: "Fórmula de despedida",
    planTitle: "Plan de desarrollo profesional",
    planActive: "Estas acciones completan directamente la plantilla de consejos.",
    planAnnex: "Se conserva como anexo editable cuando el documento activo es un currículum.",
    previewPreparing: "Preparando la vista previa del PDF…",
    previewUpdating: "Actualizando el PDF…",
    exactPreview: "Vista previa del PDF real: la descarga utiliza exactamente este documento.",
  },
  de: {
    subtitle: "Lebenslauf · Anschreiben · Berufsplan · Auswählbares mehrsprachiges PDF",
    document: "Dokument",
    template: "Vorlage",
    palette: "Vorlagenfarbe",
    originalColor: "Originalfarbe",
    customColor: "Benutzerdefinierte Farbe",
    language: "Dokumentsprache",
    importJson: "JSON importieren",
    example: "Beispiel",
    reset: "Zurücksetzen",
    preparingPdf: "PDF wird vorbereitet",
    downloadPdf: "PDF herunterladen",
    downloadCurrent: "Aktuelle Vorlage · 7 Sprachen (.zip)",
    downloadCurrentHint: commonDownloadHint,
    downloadPack: "Komplettes Paket herunterladen (.zip)",
    downloadPackHint: "81 PDFs · arabische Vorlagen nur auf Arabisch",
    preparingPack: "Paket wird erstellt",
    packReady: "Paket heruntergeladen: 81 PDFs, davon 4 spezielle arabische Vorlagen.",
    currentPackReady: "Aktuelle Vorlage in allen 7 Sprachen heruntergeladen.",
    packError: "Das komplette Paket konnte nicht erstellt werden.",
    resetConfirm: "Deutsche Daten zurücksetzen?",
    previewError: "Die PDF-Vorschau konnte nicht erstellt werden.",
    jsonImported: "JSON importiert:",
    importError: "Unbekannter Fehler beim Import.",
    personal: "Persönliche Angaben",
    letterTitle: "Anschreiben",
    letterActive: "Diese Felder füllen das ausgewählte Anschreiben direkt aus.",
    letterAnnex: "Bleibt als bearbeitbare Anlage erhalten, solange ein Lebenslauf aktiv ist.",
    date: "Datum",
    subject: "Betreff",
    recipient: "Empfänger",
    greeting: "Anrede",
    paragraphs: "Absätze",
    closing: "Grußformel",
    planTitle: "Beruflicher Entwicklungsplan",
    planActive: "Diese Maßnahmen füllen die Beratungsvorlage direkt aus.",
    planAnnex: "Bleibt als bearbeitbare Anlage erhalten, solange ein Lebenslauf aktiv ist.",
    previewPreparing: "PDF-Vorschau wird vorbereitet…",
    previewUpdating: "PDF wird aktualisiert…",
    exactPreview: "Vorschau der tatsächlichen PDF — der Download verwendet genau dieses Dokument.",
  },
  it: {
    subtitle:
      "Curriculum · Lettere di presentazione · Piano professionale · PDF multilingue selezionabile",
    document: "Documento",
    template: "Modello",
    palette: "Colore del modello",
    originalColor: "Colore originale",
    customColor: "Colore personalizzato",
    language: "Lingua del documento",
    importJson: "Importa JSON",
    example: "Esempio",
    reset: "Reimposta",
    preparingPdf: "Preparazione PDF",
    downloadPdf: "Scarica PDF",
    downloadCurrent: "Modello attuale · 7 lingue (.zip)",
    downloadCurrentHint: commonDownloadHint,
    downloadPack: "Scarica il pacchetto completo (.zip)",
    downloadPackHint: "81 PDF · modelli arabi solo in arabo",
    preparingPack: "Creazione del pacchetto",
    packReady: "Pacchetto scaricato: 81 PDF, inclusi 4 modelli arabi dedicati.",
    currentPackReady: "Modello attuale scaricato in tutte le 7 lingue.",
    packError: "Impossibile creare il pacchetto completo.",
    resetConfirm: "Reimpostare i dati italiani?",
    previewError: "Impossibile generare l’anteprima PDF.",
    jsonImported: "JSON importato:",
    importError: "Errore sconosciuto durante l’importazione.",
    personal: "Informazioni personali",
    letterTitle: "Lettera di presentazione",
    letterActive: "Questi campi compilano direttamente la lettera selezionata.",
    letterAnnex: "Conservata come allegato modificabile quando è attivo un curriculum.",
    date: "Data",
    subject: "Oggetto",
    recipient: "Destinatario",
    greeting: "Formula di apertura",
    paragraphs: "Paragrafi",
    closing: "Formula di chiusura",
    planTitle: "Piano di sviluppo professionale",
    planActive: "Queste azioni compilano direttamente il modello dei consigli.",
    planAnnex: "Conservato come allegato modificabile quando è attivo un curriculum.",
    previewPreparing: "Preparazione dell’anteprima PDF…",
    previewUpdating: "Aggiornamento del PDF…",
    exactPreview: "Anteprima del PDF reale: il download utilizza esattamente questo documento.",
  },
  zh: {
    subtitle: "简历 · 求职信 · 职业规划 · 可选择语言的多语言 PDF",
    document: "文档",
    template: "模板",
    palette: "模板颜色",
    originalColor: "原始颜色",
    customColor: "自定义颜色",
    language: "文档语言",
    importJson: "导入 JSON",
    example: "示例",
    reset: "重置",
    preparingPdf: "正在准备 PDF",
    downloadPdf: "下载 PDF",
    downloadCurrent: "当前模板 · 7 种语言 (.zip)",
    downloadCurrentHint: commonDownloadHint,
    downloadPack: "下载完整套件 (.zip)",
    downloadPackHint: "81 份 PDF · 阿拉伯语模板仅提供阿拉伯语版本",
    preparingPack: "正在创建套件",
    packReady: "套件已下载：共 81 份 PDF，其中包含 4 个专用阿拉伯语模板。",
    currentPackReady: "当前模板已下载为全部 7 种语言版本。",
    packError: "无法创建完整套件。",
    resetConfirm: "是否重置中文数据？",
    previewError: "无法生成 PDF 预览。",
    jsonImported: "已导入 JSON：",
    importError: "导入时发生未知错误。",
    personal: "个人信息",
    letterTitle: "求职信",
    letterActive: "这些字段会直接填入所选求职信。",
    letterAnnex: "当前文档为简历时，求职信内容会作为可编辑附件保留。",
    date: "日期",
    subject: "主题",
    recipient: "收件人",
    greeting: "称呼",
    paragraphs: "正文段落",
    closing: "结束语",
    planTitle: "职业发展计划",
    planActive: "这些行动会直接填入职业建议模板。",
    planAnnex: "当前文档为简历时，该计划会作为可编辑附件保留。",
    previewPreparing: "正在准备 PDF 预览…",
    previewUpdating: "正在更新 PDF…",
    exactPreview: "真实 PDF 预览——下载时使用的正是此文档。",
  },
  ar: {
    subtitle: "السيرة الذاتية · رسائل التحفيز · الخطة المهنية · ملف PDF متعدد اللغات",
    document: "المستند",
    template: "النموذج",
    palette: "لون النموذج",
    originalColor: "اللون الأصلي",
    customColor: "لون مخصص",
    language: "لغة المستند",
    importJson: "استيراد JSON",
    example: "مثال",
    reset: "إعادة التعيين",
    preparingPdf: "جارٍ إعداد PDF",
    downloadPdf: "تنزيل PDF",
    downloadCurrent: "النموذج الحالي · 7 لغات (.zip)",
    downloadCurrentHint: commonDownloadHint,
    downloadPack: "تنزيل الحزمة الكاملة (.zip)",
    downloadPackHint: "81 ملف PDF · النماذج العربية متاحة بالعربية فقط",
    preparingPack: "جارٍ إنشاء الحزمة",
    packReady: "تم تنزيل الحزمة: 81 ملف PDF، منها 4 نماذج عربية مخصصة.",
    currentPackReady: "تم تنزيل النموذج الحالي بجميع اللغات السبع.",
    packError: "تعذر إنشاء الحزمة الكاملة.",
    resetConfirm: "هل تريد إعادة تعيين البيانات العربية؟",
    previewError: "تعذر إنشاء معاينة PDF.",
    jsonImported: "تم استيراد JSON:",
    importError: "حدث خطأ غير معروف أثناء الاستيراد.",
    personal: "المعلومات الشخصية",
    letterTitle: "رسالة التحفيز",
    letterActive: "تملأ هذه الحقول رسالة التحفيز المحددة مباشرةً.",
    letterAnnex: "تُحفظ كمرفق قابل للتعديل عندما تكون السيرة الذاتية هي المستند النشط.",
    date: "التاريخ",
    subject: "الموضوع",
    recipient: "المرسل إليه",
    greeting: "التحية",
    paragraphs: "الفقرات",
    closing: "صيغة الختام",
    planTitle: "خطة التطوير المهني",
    planActive: "تملأ هذه الإجراءات نموذج النصائح مباشرةً.",
    planAnnex: "تُحفظ كمرفق قابل للتعديل عندما تكون السيرة الذاتية هي المستند النشط.",
    previewPreparing: "جارٍ إعداد معاينة PDF…",
    previewUpdating: "جارٍ تحديث PDF…",
    exactPreview: "معاينة ملف PDF الحقيقي — يستخدم التنزيل هذا المستند نفسه تماماً.",
  },
};

export const FORM_COPY: Record<DocumentLanguage, FormCopy> = {
  fr: {
    fullName: "Nom complet",
    jobTitle: "Titre du poste",
    phone: "Téléphone",
    address: "Adresse",
    relocation: "Statut / Relocation",
    birthDate: "Date de naissance",
    maritalStatus: "Situation familiale",
    drivingLicence: "Permis de conduire",
    nationalService: "Service national",
    region: "Wilaya / Province",
    country: "Pays",
    applicationInfo: "Informations de candidature",
    objective: "Objectif",
    skills: "Compétences clés",
    skill: "Compétence",
    add: "Ajouter",
    remove: "Retirer",
    languages: "Langues",
    french: "Français",
    english: "Anglais",
    arabic: "Arabe",
    german: "Allemand",
    spanish: "Espagnol",
    fluentExample: "ex : Courant",
    experience: "Expérience professionnelle",
    training: "Formation",
    education: "Éducation",
    volunteering: "Participation",
    certifications: "Certifications",
    interests: "Centres d’intérêt",
    references: "Références",
    dates: "Dates",
    place: "Lieu",
    title: "Titre",
    employer: "Employeur",
    achievements: "Réalisations",
    addLine: "Ajouter une ligne",
    delete: "Supprimer",
    institution: "Institution",
    acquiredSkills: "Compétences acquises",
    option: "Option",
    equivalence: "Équivalence",
    noItems: "Aucun élément.",
    recipientPlaceholder: "Nom du destinataire",
    greetingPlaceholder: "ex. Madame, Monsieur,",
  },
  en: {
    fullName: "Full name",
    jobTitle: "Job title",
    phone: "Phone",
    address: "Address",
    relocation: "Status / Relocation",
    birthDate: "Date of birth",
    maritalStatus: "Marital status",
    drivingLicence: "Driver’s licence",
    nationalService: "National service",
    region: "Province / Region",
    country: "Country",
    applicationInfo: "Application information",
    objective: "Professional objective",
    skills: "Key skills",
    skill: "Skill",
    add: "Add",
    remove: "Remove",
    languages: "Languages",
    french: "French",
    english: "English",
    arabic: "Arabic",
    german: "German",
    spanish: "Spanish",
    fluentExample: "e.g. Fluent",
    experience: "Professional experience",
    training: "Training",
    education: "Education",
    volunteering: "Volunteering & activities",
    certifications: "Certifications",
    interests: "Interests",
    references: "References",
    dates: "Dates",
    place: "Location",
    title: "Title",
    employer: "Employer",
    achievements: "Achievements",
    addLine: "Add a line",
    delete: "Delete",
    institution: "Institution",
    acquiredSkills: "Skills acquired",
    option: "Specialization",
    equivalence: "Equivalence",
    noItems: "No items.",
    recipientPlaceholder: "Recipient name",
    greetingPlaceholder: "e.g. Dear Sir or Madam,",
  },
  es: {
    fullName: "Nombre completo",
    jobTitle: "Puesto",
    phone: "Teléfono",
    address: "Dirección",
    relocation: "Estado / Reubicación",
    birthDate: "Fecha de nacimiento",
    maritalStatus: "Estado civil",
    drivingLicence: "Permiso de conducir",
    nationalService: "Servicio nacional",
    region: "Provincia / Región",
    country: "País",
    applicationInfo: "Información de candidatura",
    objective: "Objetivo profesional",
    skills: "Competencias clave",
    skill: "Competencia",
    add: "Añadir",
    remove: "Quitar",
    languages: "Idiomas",
    french: "Francés",
    english: "Inglés",
    arabic: "Árabe",
    german: "Alemán",
    spanish: "Español",
    fluentExample: "p. ej. Fluido",
    experience: "Experiencia profesional",
    training: "Formación",
    education: "Educación",
    volunteering: "Voluntariado y actividades",
    certifications: "Certificaciones",
    interests: "Intereses",
    references: "Referencias",
    dates: "Fechas",
    place: "Lugar",
    title: "Título",
    employer: "Empleador",
    achievements: "Logros",
    addLine: "Añadir una línea",
    delete: "Eliminar",
    institution: "Institución",
    acquiredSkills: "Competencias adquiridas",
    option: "Especialidad",
    equivalence: "Equivalencia",
    noItems: "Ningún elemento.",
    recipientPlaceholder: "Nombre del destinatario",
    greetingPlaceholder: "p. ej. Estimado señor o señora,",
  },
  de: {
    fullName: "Vollständiger Name",
    jobTitle: "Berufsbezeichnung",
    phone: "Telefon",
    address: "Adresse",
    relocation: "Status / Umzugsbereitschaft",
    birthDate: "Geburtsdatum",
    maritalStatus: "Familienstand",
    drivingLicence: "Führerschein",
    nationalService: "Wehrdienst",
    region: "Bundesland / Region",
    country: "Land",
    applicationInfo: "Bewerbungsinformationen",
    objective: "Berufliches Ziel",
    skills: "Kernkompetenzen",
    skill: "Kompetenz",
    add: "Hinzufügen",
    remove: "Entfernen",
    languages: "Sprachen",
    french: "Französisch",
    english: "Englisch",
    arabic: "Arabisch",
    german: "Deutsch",
    spanish: "Spanisch",
    fluentExample: "z. B. fließend",
    experience: "Berufserfahrung",
    training: "Weiterbildung",
    education: "Ausbildung",
    volunteering: "Ehrenamt und Aktivitäten",
    certifications: "Zertifizierungen",
    interests: "Interessen",
    references: "Referenzen",
    dates: "Zeitraum",
    place: "Ort",
    title: "Titel",
    employer: "Arbeitgeber",
    achievements: "Erfolge",
    addLine: "Zeile hinzufügen",
    delete: "Löschen",
    institution: "Institution",
    acquiredSkills: "Erworbene Kompetenzen",
    option: "Schwerpunkt",
    equivalence: "Anerkennung",
    noItems: "Keine Einträge.",
    recipientPlaceholder: "Name des Empfängers",
    greetingPlaceholder: "z. B. Sehr geehrte Damen und Herren,",
  },
  it: {
    fullName: "Nome completo",
    jobTitle: "Posizione",
    phone: "Telefono",
    address: "Indirizzo",
    relocation: "Stato / Trasferimento",
    birthDate: "Data di nascita",
    maritalStatus: "Stato civile",
    drivingLicence: "Patente di guida",
    nationalService: "Servizio nazionale",
    region: "Provincia / Regione",
    country: "Paese",
    applicationInfo: "Informazioni sulla candidatura",
    objective: "Obiettivo professionale",
    skills: "Competenze chiave",
    skill: "Competenza",
    add: "Aggiungi",
    remove: "Rimuovi",
    languages: "Lingue",
    french: "Francese",
    english: "Inglese",
    arabic: "Arabo",
    german: "Tedesco",
    spanish: "Spagnolo",
    fluentExample: "es. Fluente",
    experience: "Esperienza professionale",
    training: "Formazione",
    education: "Istruzione",
    volunteering: "Volontariato e attività",
    certifications: "Certificazioni",
    interests: "Interessi",
    references: "Referenze",
    dates: "Date",
    place: "Luogo",
    title: "Titolo",
    employer: "Datore di lavoro",
    achievements: "Risultati",
    addLine: "Aggiungi una riga",
    delete: "Elimina",
    institution: "Istituzione",
    acquiredSkills: "Competenze acquisite",
    option: "Specializzazione",
    equivalence: "Equipollenza",
    noItems: "Nessun elemento.",
    recipientPlaceholder: "Nome del destinatario",
    greetingPlaceholder: "es. Gentile responsabile della selezione,",
  },
  zh: {
    fullName: "姓名",
    jobTitle: "职位",
    phone: "电话",
    address: "地址",
    relocation: "状态 / 搬迁意愿",
    birthDate: "出生日期",
    maritalStatus: "婚姻状况",
    drivingLicence: "驾驶证",
    nationalService: "兵役情况",
    region: "省 / 地区",
    country: "国家",
    applicationInfo: "求职信息",
    objective: "职业目标",
    skills: "核心技能",
    skill: "技能",
    add: "添加",
    remove: "移除",
    languages: "语言",
    french: "法语",
    english: "英语",
    arabic: "阿拉伯语",
    german: "德语",
    spanish: "西班牙语",
    fluentExample: "例如：流利",
    experience: "工作经历",
    training: "专业培训",
    education: "教育背景",
    volunteering: "志愿服务与活动",
    certifications: "证书",
    interests: "兴趣爱好",
    references: "推荐人",
    dates: "日期",
    place: "地点",
    title: "名称",
    employer: "雇主",
    achievements: "主要成果",
    addLine: "添加一行",
    delete: "删除",
    institution: "机构",
    acquiredSkills: "所获技能",
    option: "专业方向",
    equivalence: "学历认证",
    noItems: "暂无内容。",
    recipientPlaceholder: "收件人姓名",
    greetingPlaceholder: "例如：尊敬的招聘负责人：",
  },
  ar: {
    fullName: "الاسم الكامل",
    jobTitle: "المسمى الوظيفي",
    phone: "الهاتف",
    address: "العنوان",
    relocation: "الحالة / الاستعداد للانتقال",
    birthDate: "تاريخ الميلاد",
    maritalStatus: "الحالة العائلية",
    drivingLicence: "رخصة القيادة",
    nationalService: "الخدمة الوطنية",
    region: "الولاية / المنطقة",
    country: "البلد",
    applicationInfo: "معلومات الترشح",
    objective: "الهدف المهني",
    skills: "المهارات الأساسية",
    skill: "مهارة",
    add: "إضافة",
    remove: "إزالة",
    languages: "اللغات",
    french: "الفرنسية",
    english: "الإنجليزية",
    arabic: "العربية",
    german: "الألمانية",
    spanish: "الإسبانية",
    fluentExample: "مثال: بطلاقة",
    experience: "الخبرة المهنية",
    training: "التكوين",
    education: "التعليم",
    volunteering: "التطوع والأنشطة",
    certifications: "الشهادات",
    interests: "الاهتمامات",
    references: "المراجع",
    dates: "الفترة",
    place: "المكان",
    title: "العنوان",
    employer: "جهة العمل",
    achievements: "الإنجازات",
    addLine: "إضافة سطر",
    delete: "حذف",
    institution: "المؤسسة",
    acquiredSkills: "المهارات المكتسبة",
    option: "التخصص",
    equivalence: "المعادلة",
    noItems: "لا توجد عناصر.",
    recipientPlaceholder: "اسم المرسل إليه",
    greetingPlaceholder: "مثال: السيد أو السيدة مسؤول التوظيف المحترم،",
  },
};
